# podman-compose.rpi4.yml — RPi4 overrides
# Extends podman-compose.yml with RPi4 specific hardware.
#
# Usage on RPi4:
#   podman-compose -f podman-compose.yml -f podman-compose.rpi4.yml up -d
#
# What this adds:
#   - V4L2 M2M hardware H.264 encoder devices (/dev/video10-12)
#   - Uses pre-built ghcr.io image instead of building locally
#   - Sets CAMERA_DEVICE=0 (USB camera on RPi)

version: "3.9"

services:
  backend:
    # Pull pre-built image from ghcr.io instead of building
    image: ghcr.io/mgrossu/home-surveillance-system:latest
    build: !reset null
    devices:
      - /dev/video0:/dev/video0
      - /dev/video10:/dev/video10   # RPi4 H.264 hardware encoder
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    environment:
      - CAMERA_DEVICE=0
      - RTSP_URL=rtsp://mediamtx:8554/cam
      - RECORDINGS_DIR=/recordings
      - UI_DIST=/app/frontend/dist
      - DEV_MODE=false